# Computation with NumPy and N-Dimensional Arrays

The crown jewel of NumPy is the `ndarray`. The **ndarray** is a *homogeneous n-dimensional array* object. What does that mean? 🤨

A Python List or a Pandas DataFrame can contain a mix of strings, numbers, or objects (i.e., a mix of different types). **Homogenous** means all the data have to have the same data type, for example all floating-point numbers.

And **n-dimensional** means that we can work with everything from a single column (1-dimensional) to the matrix (2-dimensional) to a bunch of matrices stacked on top of each other (n-dimensional).

In [1]:
import numpy as np 

import matplotlib.pyplot as plt 
from scipy import misc 
from PIL import Image

#### 1-Dimension

In [2]:
# Create a 1-dimensional array (i.e., a “vector”)

my_array = np.array([1.1, 9.2, 8.1, 4.7])

In [3]:
my_array.shape

(4,)

In [5]:
#We access an element in a ndarray similar to how we work with a Python List, namely by that element's index:

my_array[2]

8.1

In [6]:
# Check the dimensions of my_array with the ndim attribute:

my_array.ndim

1

#### 2-Dimensions

In [7]:
# Create a 2-dimensional array (i.e., a “matrix”)

array_2d = np.array([[1, 2, 3, 9], [5, 6, 7, 8]])

Note we have two pairs of square brackets. This array has 2 rows and 4 columns. NumPy refers to the dimensions as **axes**, so the first axis has length 2 and the second axis has length 4.

In [8]:
print(f'array_2d has {array_2d.ndim} dimensions')
print(f'Its shape is {array_2d.shape}')
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d)

array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
[[1 2 3 9]
 [5 6 7 8]]


In [9]:
# Access the 3rd value in the 2nd row:

array_2d[1,2]

7

To access an entire row and all the values therein, you can use the `:` operator just like you would do with a Python List. Here’s the entire first row:

In [10]:
array_2d[0, :]

array([1, 2, 3, 9])

#### N-Dimensions

An array of 3 dimensions (or higher) is often referred to as a ”tensor”. Yes, that’s also where Tensorflow, the popular machine learning tool, gets its name. A tensor simply refers to an n-dimensional array.

In [11]:
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

In [17]:
print(f'We have {mystery_array.ndim} dimensions')
print(f'The shape is {mystery_array.shape}')

We have 3 dimensions
The shape is (3, 2, 4)


In [18]:
# Access the value 18 in the last line of code:

mystery_array[2, 1, 3]

18

In [15]:
# Retrieve a 1-dimensional vector with the values [97, 0, 27, 18]

mystery_array[2, 1 :]

array([[97,  0, 27, 18]])

In [19]:
#  Retrieve a (3,2) matrix with the values [[ 0, 4], [ 7, 5], [ 5, 97]]

new_array = mystery_array[:, :, 0]
new_array

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])